numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100. File automatically generated. See the documentation to update questions/answers/hints programmatically.

1. Import the numpy package under the name np (★☆☆)
hint: import … as



In [4]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros



In [ ]:
np.zeros(10)

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]



In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange



In [ ]:
np.arange(10, 50)

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape



In [9]:
y = np.arange(0,9).reshape((3,3))
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


"\n    Return the shape of an array.\n\n    Parameters\n    ----------\n    a : array_like\n        Input array.\n\n    Returns\n    -------\n    shape : tuple of ints\n        The elements of the shape tuple give the lengths of the\n        corresponding array dimensions.\n\n    See Also\n    --------\n    len\n    ndarray.shape : Equivalent array method.\n\n    Examples\n    --------\n    >>> np.shape(np.eye(3))\n    (3, 3)\n    >>> np.shape([[1, 2]])\n    (1, 2)\n    >>> np.shape([0])\n    (1,)\n    >>> np.shape(0)\n    ()\n\n    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])\n    >>> np.shape(a)\n    (2,)\n    >>> a.shape\n    (2,)\n\n    "

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero



In [10]:
z = np.array([1,2,0,0,4,0])
np.nonzero(z)

"array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,\n          like=None)\n\n    Create an array.\n\n    Parameters\n    ----------\n    object : array_like\n        An array, any object exposing the array interface, an object whose\n        __array__ method returns an array, or any (nested) sequence.\n    dtype : data-type, optional\n        The desired data-type for the array.  If not given, then the type will\n        be determined as the minimum type required to hold the objects in the\n        sequence.\n    copy : bool, optional\n        If true (default), then the object is copied.  Otherwise, a copy will\n        only be made if __array__ returns a copy, if obj is a nested sequence,\n        or if a copy is needed to satisfy any of the other requirements\n        (`dtype`, `order`, etc.).\n    order : {'K', 'A', 'C', 'F'}, optional\n        Specify the memory layout of the array. If object is not an array, the\n        newly created array will be in C orde

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye



In [13]:
q = np.eye(3,3,0)
print(q)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random



In [ ]:
d = np.random.random((3,3,3))
print(d)

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max



In [ ]:
p = np.random.random((10,10))
np.min(p)
np.max(p)

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean



In [12]:
j = np.random.random((1,30))
print(j)
np.mean(j)

[[0.5854395  0.94808982 0.9770274  0.81638091 0.60342668 0.23932486
  0.44888018 0.45351172 0.96622652 0.35985968 0.10875059 0.88478289
  0.02724274 0.04408638 0.87863847 0.32528702 0.69040806 0.4875432
  0.95839611 0.96187086 0.1155426  0.09368167 0.53847613 0.07127548
  0.72708121 0.64411735 0.65254768 0.08206659 0.63332136 0.19733972]]


0.5173541125658528

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag



In [14]:
l = np.diag((1,2,3,4), k=-1)
print(l)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std



In [86]:
er = np.random.randint(1,40, (5,5))
normalize = er - np.mean(er)/np.std(er)
print(normalize)

[[28.92604551  3.92604551 35.92604551 11.92604551 17.92604551]
 [12.92604551 33.92604551  2.92604551 29.92604551  7.92604551]
 [15.92604551 17.92604551 36.92604551 -0.07395449 32.92604551]
 [10.92604551 24.92604551 23.92604551 25.92604551 18.92604551]
 [20.92604551 14.92604551 16.92604551 13.92604551 12.92604551]]



13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d



In [100]:
u = np.random.randint(1,10, (4,4))
ou = np.random.randint(1,10, (4,4))
gro = np.intersect1d(u,ou)
print(gro)

[1 2 3 4 5 6 8 9]


14. Create a random vector of size 10 and sort it (★★☆)
hint: sort



In [112]:
qw = np.random.randint(1,11, (10))
print(qw)
np.sort(qw)

[ 1  1  7 10  6  5  9  9  2  2]


array([ 1,  1,  2,  2,  5,  6,  7,  9,  9, 10])

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax



In [17]:
kj = np.random.randint(1,11, (10))
yu = np.argmax(kj)
kj[yu] = 0
print(kj)

[1 8 6 4 1 4 6 2 0 1]


16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)



In [124]:
start = np.random.randint(1,11, (10,10))
mean = start -start.mean(axis=1, keepdims = True)
print(mean)

[[ 1.5 -0.5 -4.5  1.5  1.5 -0.5 -1.5 -1.5  2.5  1.5]
 [-2.4 -4.4  4.6 -3.4  1.6  2.6 -0.4 -1.4  4.6 -1.4]
 [-2.7 -2.7  3.3  3.3 -3.7  3.3  2.3  1.3 -1.7 -2.7]
 [ 2.6  2.6 -0.4 -0.4 -1.4 -4.4 -5.4  0.6  2.6  3.6]
 [ 1.3 -1.7  4.3 -2.7  4.3  3.3 -1.7 -2.7 -1.7 -2.7]
 [ 3.7 -2.3  2.7 -2.3 -3.3  3.7 -2.3 -3.3  0.7  2.7]
 [ 0.8  1.8 -0.2  0.8 -2.2  1.8  1.8 -2.2  0.8 -3.2]
 [ 3.3 -1.7  1.3 -3.7  4.3  3.3 -2.7  3.3 -2.7 -4.7]
 [ 0.8 -2.2  2.8 -4.2  2.8  3.8 -1.2 -0.2  2.8 -5.2]
 [-0.6  2.4  1.4  0.4 -2.6 -4.6  2.4  2.4  0.4 -1.6]]


17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [ ]:
Z = np.arange(10000) np.random.shuffle(Z) n = 5

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [20]:
gh = np.random.randint(1,11, (10,10))
gs = np.where(gh > 4, gh**2, gh)
print(gs)

[[ 64  64 100  81 100   2   2 100  49  64]
 [ 49  25  36   3 100   2  81  81   4  81]
 [ 81 100  36   3   1 100  49 100   4 100]
 [ 49  36   3  49  25  64  36 100   3  36]
 [ 25   2  81 100 100   1   3  64  64  49]
 [100   1   2  36   4   4  64  81 100  25]
 [  3  25   4  25   4  64   1   1  36   4]
 [  3   1   2   2  25  36   1  25   2   4]
 [  2  25   3   2  25  49  25  81  81 100]
 [ 81  36   1 100   1   2   3  36  81 100]]
