## Pandas Data Frames

- What Is Pandas?
- Pandas vs Numpy 
- Pandas Data Frame Intro
- Pandas Data Frame fundamental operations
    - Creating
    - Selecting/indexing
    - Inserting rows/columns
    - Setting data
    - Filtering
    - dropping rwos/ columns
- Dealing with Missing values

%matplotlib inline
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.display import HTML
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))


CSS = """
.output {
    align-items: center;
}
"""
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Code mode"></form>''')

In [1]:
from IPython.display import display,Image, HTML

CSS = """
.output {
    align-items: center;
}
div.output_area {
    width: 80%;
}
"""
HTML('<style>{}</style>'.format(CSS))

# What is Pandas?

### - Enables working with tabular and labeled data easily and intuitively
### - Pandas is an open-source library built on top of Numpy Package.
- https://github.com/pandas-dev/pandas
- https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/core/frame.py

### - Pandas data structures are:
    - Series
    - Index
    - Data Frame
    

## Quick refresh to Numpy Arrays..
- contains Numerical ***Homogonius*** Data
- may contain multi dimensional array elements.
- used for performing various numerical computations and processing of the multidimensional and single-dimensional array elements.

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

two_dim_arr = np.random.randint(10, size=(3, 4))  # Two-dimensional array
three_dim_arr = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


### A two dimensional Array example...

In [3]:
print("Two Dimentional Array")
two_dim_arr

Two Dimentional Array


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

### What I mean by Homogeneous...

In [4]:
print(two_dim_arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


**two_dim_arr[0,0] = "Hello"**

In [5]:
#printmd("***Oops....***")
two_dim_arr[0,0] = "Hello" 

ValueError: invalid literal for int() with base 10: 'Hello'

### You can directly and simply form the DataFrame from the 2D array

In [7]:
import pandas as pd

In [ ]:

print("Data Frame formed by 2D Array")
#printmd("***df=pd.DataFrame(two_dim_arr)***")
df=pd.DataFrame(two_dim_arr)
df

### Pandas Data Frame is Heterogeneous!
**df.iloc[0,0]="Hello"**

In [ ]:
df.iloc[0,0]="Hello"
df

### Pandas Data Frame labels the data with Indices and Columns labels
pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

In [ ]:
np.random.randint(10,size=(3,2))

In [ ]:
##np.random.seed(0)
foo_df=pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c']
                   )

In [ ]:
foo_df

In [ ]:
foo_df

### Pandas DataFrame is relevant for statistical observations/data points with various variables (categorical, etc) 

In [ ]:
Image("res/Tidy_census.png")

### It is intuitive...  Look how convenient it is!!

In [ ]:
people_df= pd.read_csv("data/people.csv")
people_df

In [ ]:
Image('res/excel-to-pandas.png')

source: https://jalammar.github.io/

### Describing the Data Frame...
- df.Info()
- df.count())
- df.describe())
- df.mean())

In [ ]:
people_df

In [ ]:
people_df.info()

In [ ]:
people_df.describe()

In [ ]:
people_df.count()

In [ ]:
x=[1,3,4,50]
print(np.median(x))
print(np.mean(x))

In [ ]:
#print(df,"\n")
people_df.info()
#print("df.count()  \n",df.count())
#print("\n df.describe() \n",df.describe())
#print("\n df.mean() \n",df.mean())

### Pandas Data Frame operations

In [ ]:
Image("res/CRUD.png")

### Data Frame creation
You can create/form a Data Frame from:
- Dict of 1D ndarrays, lists, dicts, or Series

- 2-D numpy.ndarray

- Structured or record ndarray

- A Series

- Another DataFrame

#### Here is an example...

In [ ]:
print('dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}\n')

dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}

dic

In [ ]:
df=pd.DataFrame(dic)

#### creating Index for the Data frame...

In [ ]:
df=pd.DataFrame(dic,index=["a", "b", "c", "d"])
df

In [ ]:
np.array(df["col1"])

### Creating Data frame from Pandas Series objects.. 

In [ ]:
d = {
       "apples": [3, 2, 0,1],
        "oranges": [0, 3, 7, 2],
    }

pd.DataFrame(d)

In [ ]:
Image("res/series-and-dataframe.width-1200.png")

source: https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png

### Data Frame Selection / Indexing

In [ ]:
data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]
students_df = pd.DataFrame(data=data, index=row_labels)
students_df

In [ ]:
students_df.index

Source: https://realpython.com/

### data Selection

In [ ]:
students_df.loc[[101],["age"]]

In [ ]:
students_df

### Selecting by Label
- .loc[]  function

In [ ]:
#print("students_df.loc[:, 'city']")
#students_df.loc[:, 'city']

In [ ]:
print("students_df.loc[102:106, ['name', 'city']]")
students_df.loc[102,:'city']

In [ ]:
#print('df["city"]')
cities = students_df[["age","city"]]
cities

In [ ]:
print("df.city")
students_df.city

### Selecting by Position
- .iloc[]

In [ ]:
students_df

In [ ]:
students_df.iloc[0,1]

In [ ]:
print("students_df.iloc[1:6, [0, 1]]")
students_df.iloc[1:6, [0, 1]]

### Hmm.. Can you tell what is the difference between loc and iloc?

### Setting/ Updating data

#### let us first update the Data frame index..

In [ ]:
students_df

In [ ]:
students_df.index = list(np.arange(0, 7))
students_df

In [ ]:
students_df=students_df.reset_index()

In [ ]:
students_df.index

In [ ]:
students_df.iloc[:4, 4] = [40, 50, 60, 70]
students_df

In [ ]:
students_df.loc[5, 'py-score'] 

In [ ]:
students_df.loc[5, 'py-score'] = 70
students_df

In [ ]:
students_df.loc[:,"py-score"]=90 
students_df

In [ ]:
students_df.iloc[:, -1] = [88.0, 90, 81.0, 80.0, 68.0, 61.0, 84.0]
students_df

In [ ]:
students_df["py-score"]="Adam-score"
students_df

In [ ]:
students_df

In [ ]:
students_df.info()

In [ ]:
students_df["py-score"]=students_df["py-score"]  * 1.5

In [ ]:
students_df

In [ ]:
students_df["py-score"]=list(map(lambda x: x+10,students_df["py-score"]))

In [ ]:
students_df["py-score"] +=  10


In [ ]:
students_df

In [ ]:
students_df["py-score"]= students_df["py-score"] + students_df["age"]

In [ ]:
students_df

In [ ]:
students_df.columns = ['index', 'name', 'city', 'age', 'py-score']

In [ ]:
students_df

In [ ]:
students_df[["age","py-score"]]

In [ ]:
type(students_df[["age"]])

### Inserting/deleteing rows

In [ ]:
students_df.columns


In [ ]:
students_df  = students_df[['name', 'city', 'age', 'py-score']]
students_df

In [6]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4])
students_df= students_df.append(Ronald,ignore_index=True)
students_df

NameError: name 'pd' is not defined

In [ ]:
students_df.iloc[7,:]

In [9]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4],name=21)

NameError: name 'students_df' is not defined

In [8]:
students_df=students_df.append(Ronald, ignore_index=True)


NameError: name 'students_df' is not defined

In [ ]:
students_df

In [ ]:
students_df.drop(labels=[7],inplace=True)

In [ ]:
students_df

### Inserting/Deleting columns

In [ ]:
#print('df[js-score] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0])')
students_df['js-score'] =[71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0]
students_df

In [ ]:
students_df['py-score-updated'] = students_df['py-score'] * 10 

In [ ]:
students_df

### Inserting in a specific location

In [ ]:
#print('df.insert(loc=4, column=js-score,value=np.array([86.0, 81.0, 78.0, 88.0, 74.0, 70.0, 81.0]))')
students_df.insert(loc=4, column='django-score',
          value=np.array([70, 74, 78, 56, 66, 78, 81.0]))
students_df

### dropping specific column

In [ ]:

## axis= 0 dropping by row,  axis=1. ropping by column
students_df = students_df.drop(labels=['django-score'], axis=1)

In [ ]:
students_df

### Filtering/Boolean Indexing

In [ ]:
students_df["py-score"] >= 200

In [ ]:
students_df[students_df["py-score"]>=200]

In [ ]:
very_good_students_filter = students_df['py-score'] >= 200
very_good_students_filter

In [ ]:
students_df[very_good_students_filter]

### Creating powerful filters with Logical operators AND, OR, NOT, XOR

In [ ]:
#print('df[(df[py-score] >= 80) & (df[js-score] >= 80)]')
students_df[(students_df['py-score'] >= 200) | (students_df['js-score'] >= 80)]

## using value counts  function

In [ ]:
people_df=pd.read_csv("data/people.csv")
people_df

In [ ]:
people_df["country"].value_counts()